### PR TITLE
Update pgblitz.sh

### PR DESCRIPTION
**Pull request by rla999**
Support for more apps in cleanup of empty directories.
Also excludes DL/processing/temp directories related to JDownloader2, Handbrake, and MakeMKV from being uploaded to the cloud.

### CODE REVIEW

**Comment by robertbaker** [comment]
Change **/* to ** like the other line

**Comment by robertbaker** [comment]
A better way would be to read /var/plexguide/app.list and app.list2 and build the exclude the apps dynamically.

Can you do that instead?

**Comment by rla999** [comment]
Don't know enough about scripting to do that but it's an interesting idea but I think my suggestion of just adding in those three apps paths is good for now but yeah dynamic is always better.

**Comment by robertbaker** [comment]
Fix is out, redeploy mounts.

**Pull request closed without merging**
